package Clases;
// Generated 24 feb. 2020 17:44:30 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cartas generated by hbm2java
 */
public class Cartas implements java.io.Serializable {

	private Integer idCarta;
	private String marca;
	private String modelo;
	private String foto;
	private int motor;
	private int potencia;
	private int velocidadMaxima;
	private int cilindrada;
	private int revolucionesPorMinuto;
	private float consumo;
	private Set<Jugadas> jugadases = new HashSet<Jugadas>(0);

	public Cartas() {
	}

	public Cartas(String marca, String modelo, String foto, int motor, int potencia, int velocidadMaxima,
			int cilindrada, int revolucionesPorMinuto, float consumo) {
		this.marca = marca;
		this.modelo = modelo;
		this.foto = foto;
		this.motor = motor;
		this.potencia = potencia;
		this.velocidadMaxima = velocidadMaxima;
		this.cilindrada = cilindrada;
		this.revolucionesPorMinuto = revolucionesPorMinuto;
		this.consumo = consumo;
	}

	public Cartas(String marca, String modelo, String foto, int motor, int potencia, int velocidadMaxima,
			int cilindrada, int revolucionesPorMinuto, float consumo, Set<Jugadas> jugadases) {
		this.marca = marca;
		this.modelo = modelo;
		this.foto = foto;
		this.motor = motor;
		this.potencia = potencia;
		this.velocidadMaxima = velocidadMaxima;
		this.cilindrada = cilindrada;
		this.revolucionesPorMinuto = revolucionesPorMinuto;
		this.consumo = consumo;
		this.jugadases = jugadases;
	}

	public Integer getIdCarta() {
		return this.idCarta;
	}

	public void setIdCarta(Integer idCarta) {
		this.idCarta = idCarta;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public int getMotor() {
		return this.motor;
	}

	public void setMotor(int motor) {
		this.motor = motor;
	}

	public int getPotencia() {
		return this.potencia;
	}

	public void setPotencia(int potencia) {
		this.potencia = potencia;
	}

	public int getVelocidadMaxima() {
		return this.velocidadMaxima;
	}

	public void setVelocidadMaxima(int velocidadMaxima) {
		this.velocidadMaxima = velocidadMaxima;
	}

	public int getCilindrada() {
		return this.cilindrada;
	}

	public void setCilindrada(int cilindrada) {
		this.cilindrada = cilindrada;
	}

	public int getRevolucionesPorMinuto() {
		return this.revolucionesPorMinuto;
	}

	public void setRevolucionesPorMinuto(int revolucionesPorMinuto) {
		this.revolucionesPorMinuto = revolucionesPorMinuto;
	}

	public float getConsumo() {
		return this.consumo;
	}

	public void setConsumo(float consumo) {
		this.consumo = consumo;
	}

	public Set<Jugadas> getJugadases() {
		return this.jugadases;
	}

	public void setJugadases(Set<Jugadas> jugadases) {
		this.jugadases = jugadases;
	}

}
