package Clases;
// Generated 24 feb. 2020 17:44:30 by Hibernate Tools 5.2.12.Final

/**
 * Jugadas generated by hbm2java
 */
public class Jugadas implements java.io.Serializable {

	private Integer idJugada;
	private Cartas cartas;
	private String sesion;
	private String caracteristica;
	private String jugador;
	private int mano;

	public Jugadas() {
	}

	public Jugadas(Cartas cartas, String sesion, String caracteristica, String jugador, int mano) {
		this.cartas = cartas;
		this.sesion = sesion;
		this.caracteristica = caracteristica;
		this.jugador = jugador;
		this.mano = mano;
	}

	public Integer getIdJugada() {
		return this.idJugada;
	}

	public void setIdJugada(Integer idJugada) {
		this.idJugada = idJugada;
	}

	public Cartas getCartas() {
		return this.cartas;
	}

	public void setCartas(Cartas cartas) {
		this.cartas = cartas;
	}

	public String getSesion() {
		return this.sesion;
	}

	public void setSesion(String sesion) {
		this.sesion = sesion;
	}

	public String getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(String caracteristica) {
		this.caracteristica = caracteristica;
	}

	public String getJugador() {
		return this.jugador;
	}

	public void setJugador(String jugador) {
		this.jugador = jugador;
	}

	public int getMano() {
		return this.mano;
	}

	public void setMano(int mano) {
		this.mano = mano;
	}

}
