package Clases;
// Generated 24 feb. 2020 17:44:30 by Hibernate Tools 5.2.12.Final

/**
 * Partidas generated by hbm2java
 */
public class Partidas implements java.io.Serializable {

	private Integer id;
	private Jugadores jugadores;
	private Integer puntuacionJugador;
	private Integer puntuacionCpu;
	private String ganadorPartida;
	private String sesion;
	private boolean finalizada;

	public Partidas() {
	}

	public Partidas(boolean finalizada) {
		this.finalizada = finalizada;
	}

	public Partidas(Jugadores jugadores, Integer puntuacionJugador, Integer puntuacionCpu, String ganadorPartida,
			String sesion, boolean finalizada) {
		this.jugadores = jugadores;
		this.puntuacionJugador = puntuacionJugador;
		this.puntuacionCpu = puntuacionCpu;
		this.ganadorPartida = ganadorPartida;
		this.sesion = sesion;
		this.finalizada = finalizada;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Jugadores getJugadores() {
		return this.jugadores;
	}

	public void setJugadores(Jugadores jugadores) {
		this.jugadores = jugadores;
	}

	public Integer getPuntuacionJugador() {
		return this.puntuacionJugador;
	}

	public void setPuntuacionJugador(Integer puntuacionJugador) {
		this.puntuacionJugador = puntuacionJugador;
	}

	public Integer getPuntuacionCpu() {
		return this.puntuacionCpu;
	}

	public void setPuntuacionCpu(Integer puntuacionCpu) {
		this.puntuacionCpu = puntuacionCpu;
	}

	public String getGanadorPartida() {
		return this.ganadorPartida;
	}

	public void setGanadorPartida(String ganadorPartida) {
		this.ganadorPartida = ganadorPartida;
	}

	public String getSesion() {
		return this.sesion;
	}

	public void setSesion(String sesion) {
		this.sesion = sesion;
	}

	public boolean isFinalizada() {
		return this.finalizada;
	}

	public void setFinalizada(boolean finalizada) {
		this.finalizada = finalizada;
	}

}
